### ISSUE TITLE
Create Role and Permissions Entities

### ISSUE THREAD

**Issue by kappsegla** [fungover/system2024#14]
Define Role and Permissions entities and set up relationships with the User entity.

**Comment by AlbinNils98** [comment]
Details required: What roles and permissons should exist? e.g. admin, dev ,user etc.

**Comment by kappsegla** [comment]
Out we could use attributes like read write delete permissions for different resources? Ex read:users. 

More fine grained than using only roles?

**Comment by MikaelaMathisson** [comment]
Conflicts that needs to be resolved before merge
