### ISSUE TITLE
Encrypt URL's before they are stored in the DB

### ISSUE THREAD

**Issue by sebastianpiresmolin** [fungover/system2024#43]
Storing file URLs directly in the database, as done in the `fileUrl` field, can pose security risks if the URLs contain sensitive information or if they are not adequately protected. Exposure of file URLs can lead to unauthorized data access.

**Recommendation:** Ensure that file URLs are stored securely and consider implementing additional security measures such as URL encryption, access controls, or using indirect references instead of direct URLs to enhance security.

_Originally posted by @codereviewbot-ai[bot] in https://github.com/fungover/system2024/pull/42#discussion_r1869845944_

**Comment by kappsegla** [comment]
I think this recommendation is primary for urls that might include for example query parameters that can hold ids or keys that get you access to information not ment for everyone. In a perfect world these ids shouldn't give access to resources directly without also cheching some extra authorization?

**Comment by sebastianpiresmolin** [comment]
You're right, there should definitely be an authority check before letting someone access one of the "secret" file download URI's anyway. So the encryption would indeed be redundant.
