### ISSUE TITLE
Create Query to Fetch a List of Users

### ISSUE THREAD

**Issue by kappsegla** [fungover/system2024#9]
Implement a GraphQL query to return a list of all users.

**Comment by AlbinNils98** [comment]
@kappsegla Needs more information: As a user is mapped to both roles and permissions, should these be implemeted as well in the schema, also, i assume the users passwords shouldn't be implemeted?

**Comment by kappsegla** [comment]
I was thinking more about user information, like name. Definitely not password. 😛 Perfect example for a case where it's useful with a dto and not trying to serialize Domain entities directly.
